name: e_commmerce1
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ">2.25.4 <3.0.0"

#environment:
#  sdk: '>=2.19.4 <4.0.0'



dependencies:
  flutter:
    sdk: flutter


  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  google_nav_bar: ^5.0.6
  iconsax: ^0.0.8
  #  firebase_core: any
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
#  sqflite: ^2.0.0
#  path: ^1.8.0
#  firebase_core: ^2.25.4





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/products/p_1.jpg
    - images/products/p_2.jpg
    - images/products/p_3.jpg
    - images/category/anarkali_crop.png
    - images/category/denim-modified.png
    - images/category/dungree-modified.png
    - images/category/gown1-modified.png
    - images/category/kurti-modified.png
    - images/category/sari1-modified.png
    - images/category/shorts.png
    - images/category/skirts-modified.png
    - images/category/sundress1-modified.png
    - images/products/anarkali.png
    - images/products/top.png
    - images/products/sadi.png
    - images/products/jumsuit.png
    - images/products/LEHNAGA.png
    - images/products/skirt.png
    - images/logo/logo.png
    - images/logo/logo_1.png
    - images/logo/pro.png
    - images/products/sale.png
    - images/products/sale2.png
    - images/products/sale3.png
    - images/products/longskirt.png




