// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC78I0T46NKH-uIaA_r3YgGUjilSAjtma8',
    appId: '1:831195346659:web:d0714baba2a562a08ff7d6',
    messagingSenderId: '831195346659',
    projectId: 'shopcart-7cf1d',
    authDomain: 'shopcart-7cf1d.firebaseapp.com',
    databaseURL: 'https://shopcart-7cf1d-default-rtdb.firebaseio.com',
    storageBucket: 'shopcart-7cf1d.appspot.com',
    measurementId: 'G-LHY3Q8TY78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcBW9gx_yQ0UO8TKbLhDQD5FOZlkxGbdE',
    appId: '1:831195346659:android:f7afd218c59c6ed28ff7d6',
    messagingSenderId: '831195346659',
    projectId: 'shopcart-7cf1d',
    databaseURL: 'https://shopcart-7cf1d-default-rtdb.firebaseio.com',
    storageBucket: 'shopcart-7cf1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8fM33239svuXn1WQhSveuer9Mcu-KPYc',
    appId: '1:831195346659:ios:32f889168041d2f58ff7d6',
    messagingSenderId: '831195346659',
    projectId: 'shopcart-7cf1d',
    databaseURL: 'https://shopcart-7cf1d-default-rtdb.firebaseio.com',
    storageBucket: 'shopcart-7cf1d.appspot.com',
    iosClientId:
        '831195346659-gvmdf8bn2bjjo1b7ru4q8qu46qphiect.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommmerce1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8fM33239svuXn1WQhSveuer9Mcu-KPYc',
    appId: '1:831195346659:ios:32f889168041d2f58ff7d6',
    messagingSenderId: '831195346659',
    projectId: 'shopcart-7cf1d',
    databaseURL: 'https://shopcart-7cf1d-default-rtdb.firebaseio.com',
    storageBucket: 'shopcart-7cf1d.appspot.com',
    iosClientId:
        '831195346659-gvmdf8bn2bjjo1b7ru4q8qu46qphiect.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommmerce1',
  );
}
